// Copyright © Advanced Micro Devices, Inc., or its affiliates.
// SPDX-License-Identifier:  MIT
#pragma once

#include "Attributes.hpp"
#include "TensorAttributes.hpp"
#include <hipdnn_frontend/Types.hpp>
#include <hipdnn_sdk/data_objects/convolution_bwd_attributes_generated.h>
#include <memory>
#include <unordered_map>
#include <vector>

namespace hipdnn_frontend::graph
{
class ConvDgradAttributes : public Attributes<ConvDgradAttributes>
{
public:
    enum class InputNames
    {
        DY = 0, // Gradient of output tensor
        W = 1 // Weights/filter tensor
    };
    typedef InputNames input_names; // NOLINT(readability-identifier-naming)

    enum class OutputNames
    {
        DX = 0 // Gradient of input tensor
    };
    typedef OutputNames output_names; // NOLINT(readability-identifier-naming)

    std::unordered_map<InputNames, std::shared_ptr<TensorAttributes>> inputs;
    std::unordered_map<OutputNames, std::shared_ptr<TensorAttributes>> outputs;

    std::vector<int64_t> pre_padding; // NOLINT(readability-identifier-naming)
    std::vector<int64_t> post_padding; // NOLINT(readability-identifier-naming)
    std::vector<int64_t> stride;
    std::vector<int64_t> dilation;
    // NOLINTNEXTLINE(readability-identifier-naming)
    ConvolutionMode convolution_mode = ConvolutionMode::CROSS_CORRELATION;

    ATTRS_DEFAULT_INPUT_TENSOR_ACCESSOR(ConvDgradAttributes, dy, InputNames::DY)
    ATTRS_DEFAULT_INPUT_TENSOR_ACCESSOR(ConvDgradAttributes, w, InputNames::W)

    ATTRS_DEFAULT_OUTPUT_TENSOR_ACCESSOR(ConvDgradAttributes, dx, OutputNames::DX)

    ATTRS_DEFAULT_MEMBER_ACCESSOR(ConvDgradAttributes, pre_padding, std::vector<int64_t>)
    ATTRS_DEFAULT_MEMBER_ACCESSOR(ConvDgradAttributes, post_padding, std::vector<int64_t>)
    ATTRS_DEFAULT_MEMBER_ACCESSOR(ConvDgradAttributes, stride, std::vector<int64_t>)
    ATTRS_DEFAULT_MEMBER_ACCESSOR(ConvDgradAttributes, dilation, std::vector<int64_t>)
    ATTRS_DEFAULT_MEMBER_ACCESSOR(ConvDgradAttributes, convolution_mode, ConvolutionMode)

    // NOLINTNEXTLINE(readability-identifier-naming)
    ConvDgradAttributes& set_padding(std::vector<int64_t> padding)
    {
        set_pre_padding(padding);
        set_post_padding(std::move(padding));
        return *this;
    }


    // Getters for convolution parameters are generated by macros above

    flatbuffers::Offset<hipdnn_sdk::data_objects::ConvolutionBwdAttributes>
        pack_attributes(flatbuffers::FlatBufferBuilder& builder) const // NOLINT
    {
        return hipdnn_sdk::data_objects::CreateConvolutionBwdAttributesDirect(builder,
                                                                              get_dy()->get_uid(),
                                                                              get_w()->get_uid(),
                                                                              get_dx()->get_uid(),
                                                                              &pre_padding,
                                                                              &post_padding,
                                                                              &stride,
                                                                              &dilation,
                                                                              toSdkType(convolution_mode));
    }
};
typedef ConvDgradAttributes Conv_dgrad_attributes;
} // namespace hipdnn_frontend::graph
